### ISSUE TITLE
Fix messed up profile name

### ISSUE THREAD

**Issue by stveit** [geteduroam/windows-app#14]
<img width="248" alt="github-issue-text" src="https://user-images.githubusercontent.com/31960753/89991108-a11bc680-dc83-11ea-9c92-2c5a9d7d24b8.png">

some profiles end up looking like this.

**Comment by pbsds** [comment]
probably an issue with the encoding we decode the XML with

**Comment by pbsds** [comment]
unable to reproduce

**Comment by stveit** [comment]
And now I am unable to reproduce after a windows update

**Comment by pbsds** [comment]
We are unable to set encoding in XElement and XDocument when using .Parse(). And we download the XMl with forced UTF-8 encoding. If this still is an issue, then it probably is WPF

**Comment by jornane** [comment]
I really cannot reproduce this any which way. Maybe the problem was server-side? Closing this for now as I can't reproduce it.
