### ISSUE TITLE
Certificate screen can be shown when only public certificates are used

### ISSUE THREAD

**Issue by jornane** [geteduroam/windows-app#26]
When installing a geteduroam profile with a server certificate from the GÉANT certificate service, the certificate screen is shown. In this case, it is the Uninett profile. This does not happen with a non-geteduroam profile, such as NTNU.

![windows-certificate](https://user-images.githubusercontent.com/767872/94060098-aa9c6080-fde3-11ea-8235-c98d99d96782.png)

**Comment by pauldekkers** [comment]
I believe this is fixed meanwhile in the new App
