### ISSUE TITLE
Debug API URL returns ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by JamesFromIT** [geteduroam/windows-app#28]
When I try to run the app in debugging mode, I get an InternetConnectionException from the DownloadDiscoveryApi method in the IdentityProviderDownloader class.

If I navigate to the URL stored in the ProviderApiUrl variable, I get ERR_NAME_NOT_RESOLVED in my browser.

**Comment by jornane** [comment]
Hi @JamesFromIT 

I've done a pretty big overhaul of the discovery downloading mechanism; fd3569b0d28a278ccf2bf7436d1fbfcfef57c5eb

I didn't see the specific error you've encountered, but maybe it's also fixed by this change?

**Comment by JamesFromIT** [comment]
Hi @jornane,

I just downloaded the files from that commit and no exception was thrown. I think 724cf39 which was commited on 8th March may have fixed this as the ProviderApiUrl variable was updated then.
